### ISSUE TITLE
Question about model init

### ISSUE THREAD

**Issue by GewelsJI** [JiaxingChai/Query_Net#1]
Hi, Jiaxing,

Congrats to present a nice work here.

I have a question is about model init: have you used the well-trained Mask2Former as initialised model, or just train it from scratch?

Best,
Daniel

**Comment by JiaxingChai** [comment]
Hi, Daniel
thanks for your question, we used the well-trained Mask2former as the initialised model. we test different pre-trained weights types (semantic, instance and panoptic), and we find there is almost no difference in our final results. In our experiments, we used the semantic-ADE20k-swinS as our base setting. because i'm busying on finding jobs this time😭, i have no free time to organize the codes and upload it to github. I'm so sorry for this, i will release it near the winter. By the way, our conception is simple, you can try to reproduce it on the base of mask2former codes or any other query-based segmentation models. https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md

best wish
Jiaxing Chai

**Comment by GewelsJI** [comment]
Thanks. Good luck with your job search.
